name: CI
on:
  push:
    branches:
      – main
    paths:
      – ‘dbscripts/**’

workflow_dispatch:

jobs:
deploy-snowflake-changes-jobs:
     runs-on: ubuntu-latest
    
steps:
  - name: checkout repository
        uses: actions/checkout@v2

      – name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x
         
      – name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{secrets.SF_WAREHOUSE}}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
        run: |
          echo “GITHUB WORKSPACE $GITHUB_WORKSPACE”
          python –version
          echo “Step 1: Initializing Schemachange”
          pip install schemachange
         
          echo “Step 2: Running Schemachange”
          schemachange -f $GITHUB_WORKSPACE/dbscripts -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE  -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY –create-change-history-table
